def Students():
    students=[
        {
            'id':1,
            'name':'Sona',
            'place':'Kannur',
            'mobile':987456321,
            'email':'s@gmail.com',
            'joinedData':'06/10/2018'
        },
        {
            'id':2,
            'name':'Sana',
            'place':'Kozhikode',
            'mobile':9874525452,
            'email':'sana@gmail.com',
            'joinedData':'06/5/2018'
        },
        {
            'id':3,
            'name':'Arya',
            'place':'Kasargod',
            'mobile':987456322,
            'email':'h@gmail.com',
            'joinedData':'04/10/2018'
        },
        {
            'id':4,
            'name':'Ammu',
            'place':'Kannur',
            'mobile':987456123,
            'email':'ammu@gmail.com',
            'joinedData':'06/01/2018'
        },
        {
            'id':5,
            'name':'Amal',
            'place':'Kanjangad',
            'mobile':9877514821,
            'email':'a12@gmail.com',
            'joinedData':'06/10/2017'
        },
        {
            'id':6,
            'name':'anagh',
            'place':'Ernakulam',
            'mobile':987485214,
            'email':'gnc125@gmail.com',
            'joinedData':'18/11/2018'
        },
        
        {
            'id':7,
            'name':'Sonal',
            'place':'Thrissur',
            'mobile':987436821,
            'email':'s7458@gmail.com',
            'joinedData':'19/10/2018'
        },
        {
            'id':8,
            'name':'Sony',
            'place':'Trivandrum',
            'mobile':852456321,
            'email':'s@gmail.com',
            'joinedData':'23/06/2018'
        },
        {
            'id':9,
            'name':'Tana',
            'place':'Thalassery',
            'mobile':7544456321,
            'email':'tata@gmail.com',
            'joinedData':'15/08/2018'
        },
        {
            'id':10,
            'name':'Tina',
            'place':'Muttom',
            'mobile':9874562321,
            'email':'tata@gmail.com',
            'joinedData':'28/02/2018'
        }
        
        
         

    ]
    return students